config/routes.rb
TextAway::Application.routes.draw do

  resources :messages, :only => [:index, :new, :create, :show]
  resources :contacts

  root 'messages#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :name, :presence => true
  validates :number, :presence => true, :numericality => true, :length => { is: 10 }
  has_many :messages

end

app/models/message.rb
class Message < ActiveRecord::Base

  before_create :send_message

  validates :body, :presence => true
  validates :to, :presence => true
  validates :from, :presence => true
  belongs_to :contact

private

  def send_message
    begin
      response = RestClient::Request.new(
          :method => :post,
          :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
          :user => ENV['TWILIO_ACCOUNT_SID'],
          :password => ENV['TWILIO_AUTH_TOKEN'],
          :payload => { :Body => body,
                        :To => to,
                        :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Contact saved"
      redirect_to contact_path(@contact)
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def destroy
    @contact = Contact.destroy(params[:id])
  end

private
  def contact_params
    params.require(:contact).permit(:name, :number)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    recipient_numbers = params[:message][:to]
    recipient_numbers.each do |number|
      @contact = Contact.find_by_number(number)
      @message = @contact.messages.new(message_params)
      @message[:to] = @contact.number
      if @message.save
        respond_to do |format|
          format.html { redirect_to message_path(@message) }
          format.js
        end
      else
        render 'new'
      end
    end
  end


  def show
    @message = Message.find(params[:id])
    @contact = Contact.find(@message.contact_id)
  end

private

  def message_params
    params.require(:message).permit(:to, :from, :body, :contact_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<br>
<br>
<%= render('layouts/errors', :object => @contact) %>

<%= form_for @contact do |f| %>
  <form class="form-horizontal" role="form">
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :number %><br>
      <%= f.text_field :number %>
    </div>
    <%= f.submit(:class => "btn btn-warning") %>
  </form>
<% end %>

app/views/contacts/index.html.erb
<% content_for(:title, "Contacts | TextAway") %>

<h2>Your contacts</h2>
<br>

<% if @contacts != nil %>
  <ul>
    <% @contacts.each do |contact| %>
      <li><%= link_to "#{contact.name}", contact_path(contact) %><br>
          <%= contact.number %></li>
          <br><br>
    <% end %>
  </ul>
<% end %>

<%= link_to "New Contact", new_contact_path, class: "btn btn-warning", type: "button" %>
<%= link_to "Home", root_path, class: "btn btn-info" %>

app/views/contacts/new.html.erb
<% content_for(:title, "New Contact | TextAway") %>

<h2>Save a new contact</h2>

<%= render 'form' %>

<br>
<br>
<br>
<%= link_to "See Contacts", contacts_path, class: "btn btn-info", type: "button" %>
<%= link_to "Home", messages_path, class: "btn btn-info" %>

app/views/contacts/show.html.erb
<% content_for(:title, "Contact Info | TextAway") %>

<h2><%= @contact.name %></h2>

<br>
<h4>Phone number</h4>
<h5>     <%= @contact.number %></h5>

<br>
<br>
<br>

<div class="bs-example">
  <%= link_to "New Contact", new_contact_path, class: "btn btn-warning", type: "button" %>
  <%= link_to "See Contacts", contacts_path, class: "btn btn-primary", type: "button" %>
  <%= link_to "Home", root_path, type: "button", class: "btn btn-success" %>
  <%= link_to "New Message", new_message_path, class: "btn btn-info", type: "button", id: "new_btn", remote: true %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

      <%= yield %>

  </div>
</body>
</html>

app/views/messages/_form.html.erb
<br>
<br>
<%= render("layouts/errors", :object => @message) %>

<%= form_for @message, remote: true do |f| %>
  <form class="form-horizontal" role="form">
    <div class="form-group">

    <% Contact.all.each do |contact| %>
        <%= check_box_tag "message[to][]", contact.number %>
        <%= label :to, contact.name %><br>
    <% end %>

    </div>
    <div class="form-group">
    <%= f.label :from, "Message from:" %><br>
    <%= f.text_field :from %><br>
    </div>
    <div class="form-group">
    <%= f.label :body, "Your message" %><br>
    <%= f.text_area :body, size: '24x6' %><br>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  </form>
<% end %>

app/views/messages/_message.html.erb
<li id="message_<%= message.id %>">
  <%= link_to "#{message.body}", message_path(message) %>
</li>
<br>

app/views/messages/create.js.erb
$('#new_message').remove();
$('#new_btn').show();
$('#message_list').append('<%= j render(@message) %>');

app/views/messages/index.html.erb
<% content_for(:title, "Messages | TextAway") %>


<h2>Messages</h2>
<br>

<% if @messages != nil %>
  <ul id="message_list">
    <%= render @messages %>
  </ul>
<% end %>

<br>
<br>
<br>

<div class="btn-group">
  <%= link_to "New Message", new_message_path, class: "btn btn-info", type: "button", id: "new_btn", remote: true %>
</div>

app/views/messages/new.html.erb
<% content_for(:title, "New Message | TextAway") %>
<h2>Send a Message</h2>


<div id="new_message">
  <%= render "form" %>
</div>

<br>
<br>
<%= link_to "Home", messages_path, class: "btn btn-info" %>

app/views/messages/new.js.erb
$('#new_btn').hide().after('<%= j render("form") %>');

app/views/messages/show.html.erb
<% content_for(:title, "Sent Message | TextAway") %>

<h2>Message details</h2>
<br>
<h4>To:</h4>
<p><%= @contact.name %></p>
<p><%= @message.to %></p>
<br>

<h4>From:</h4>
<p><%= @message.from %></p>
<br>

<h4>Text:</h4>
<p><%= @message.body %></p>
<br>

<br>
<br>
<%= link_to "Home", messages_path, class: "btn btn-info" %>